site_name: Thoát porn luận
site_description: Cách thoát khỏi cơn nghiện nội dung khiêu dâm (porn) một cách dễ dàng
site_author: duykhanh471  
repo_name: Chỉnh sửa bản dịch trên Github
repo_url: https://github.com/duy103zxc/easypeasymethod-vi

nav:
  - 'index.md'
  - 'ch01.md'
  - 'ch02.md'
  - 'ch03.md'
  - 'ch04.md'
  - 'ch05.md'
  - 'ch06.md'
  - 'ch07.md'
  - 'ch08.md'
  - 'ch09.md'
  - 'ch10.md'
  - 'ch11.md'
  - 'ch12.md'
  - 'ch13.md'
  - 'ch14.md'
  - 'ch15.md'
  - 'ch16.md'
  - 'ch17.md'
  - 'ch18.md'
  - 'ch19.md'
  - 'ch20.md'
  - 'ch21.md'
  - 'ch22.md'
  - 'ch23.md'
  - 'ch24.md'
  - 'ch25.md'
  - 'ch26.md'
  - 'ch27.md'
  - 'ch28.md'
  - 'ch29.md'
  - 'ch30.md'
  - 'ch31.md'
  - 'ch32.md'
  - 'ch33.md'
  - 'resources.md'


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
  name: material

plugins:
  - search
  - open-in-new-tab

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
extra:
  generator: false